#!/bin/sh
SCRIPTS=$1
WHERE=$2
NROUTERS=$3
ROUTER=0
while [ $ROUTER -ne $NROUTERS ]
do
  sh $SCRIPTS/USERSperROUTER4.sh $WHERE USERS  $NROUTERS $ROUTER
  ROUTER=$(( $ROUTER + 1 ))
done

rm $WHERE/USERS_MEAN_OF_$NROUTERS.dat &> /dev/null

ROUTER=0
while [ $ROUTER -ne $NROUTERS ]
do
  cat $WHERE/USERS_OF_4_$ROUTER.dat | awk -f $SCRIPTS/USERS_AVG.awk >> $WHERE/USERS_MEAN_OF_$NROUTERS.dat
  ROUTER=$(( $ROUTER + 1 ))
done
